### ISSUE TITLE
Instructions to build and use?

### ISSUE THREAD

**Issue by coolaj86** [masl123/n64RomConverter#1]
How does one build and run this?

**Comment by coolaj86** [comment]
It looks like the "manifest" file is missing, so the jar cannot be reproduced from what's in the repo (or I just don't know how to do it), but here's the instructions how to run with `java`: https://github.com/masl123/n64RomConverter/pull/2

## Example

We can use [ShufflePuck64](http://micro-64.com/features/shufflepuck64.shtml) as an example ROM to convert:

```bash
pushd ~/Downloads
curl -o ./shufflepuck64.zip http://micro-64.com/features/misc/shufflepuck64.zip
unzip ./shufflepuck64.zip
```

And we can convert it by downloading and running n64RomConverter:

```bash
git clone https://github.com/masl123/n64RomConverter

java -jar ./n64RomConverter/release/N64Converter.jar \
    -i ./shufflepuck64/Shuffle\ Puck\ 64\ \(PD\).z64 \
    -o ./shufflepuck64/Shuffle\ Puck\ 64\ \(PD\).n64
```

**Comment by masl123** [comment]
Thanks for adding the instructions.
